// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SentinelKnowledgebase.Infrastructure.Data;

#nullable disable

namespace SentinelKnowledgebase.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260409093000_PreservedLanguages")]
    partial class PreservedLanguages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            new PreservedLanguagesModelSnapshot().Build(modelBuilder);
#pragma warning restore 612, 618
        }

        private sealed class PreservedLanguagesModelSnapshot : ApplicationDbContextModelSnapshot
        {
            public void Build(ModelBuilder modelBuilder)
            {
                BuildModel(modelBuilder);
            }
        }
    }
}
