// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using SentinelKnowledgebase.Infrastructure.Data;

#nullable disable

namespace SentinelKnowledgebase.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcessedInsightTag", b =>
                {
                    b.Property<Guid>("ProcessedInsightsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProcessedInsightsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProcessedInsightTag");
                });

            modelBuilder.Entity("RawCaptureTag", b =>
                {
                    b.Property<Guid>("RawCapturesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("RawCapturesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RawCaptureTag");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.EmbeddingVector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("ProcessedInsightId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcessedInsightId1")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedInsightId")
                        .IsUnique();

                    b.HasIndex("ProcessedInsightId1");

                    b.ToTable("EmbeddingVectors");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionItems")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("KeyInsights")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("RawCaptureId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RawCaptureId")
                        .IsUnique();

                    b.ToTable("ProcessedInsights");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.RawCapture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("RawCaptures");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ProcessedInsightTag", b =>
                {
                    b.HasOne("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", null)
                        .WithMany()
                        .HasForeignKey("ProcessedInsightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelKnowledgebase.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RawCaptureTag", b =>
                {
                    b.HasOne("SentinelKnowledgebase.Domain.Entities.RawCapture", null)
                        .WithMany()
                        .HasForeignKey("RawCapturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelKnowledgebase.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.EmbeddingVector", b =>
                {
                    b.HasOne("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", null)
                        .WithOne("EmbeddingVector")
                        .HasForeignKey("SentinelKnowledgebase.Domain.Entities.EmbeddingVector", "ProcessedInsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", "ProcessedInsight")
                        .WithMany()
                        .HasForeignKey("ProcessedInsightId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedInsight");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", b =>
                {
                    b.HasOne("SentinelKnowledgebase.Domain.Entities.RawCapture", "RawCapture")
                        .WithOne("ProcessedInsight")
                        .HasForeignKey("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", "RawCaptureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawCapture");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.ProcessedInsight", b =>
                {
                    b.Navigation("EmbeddingVector");
                });

            modelBuilder.Entity("SentinelKnowledgebase.Domain.Entities.RawCapture", b =>
                {
                    b.Navigation("ProcessedInsight");
                });
#pragma warning restore 612, 618
        }
    }
}
